### ISSUE TITLE
Cannot use Intellij Diagrams

### ISSUE THREAD

**Issue by airborn** [mallowigi/material-theme-jetbrains-extended#10]
I don't fully understand how this works, but after changing theme i cannot use [Diagrams](https://www.jetbrains.com/help/idea/2017.1/viewing-diagram.html)

I'm not receiving any errors, diagrams just simply don't show. After switching back to default theme everything works as expected.

**Comment by mallowigi** [comment]
![image](https://cloud.githubusercontent.com/assets/5015756/24962972/0ccd67a6-1fa6-11e7-96ed-f141a6e4f19c.png)

I don't have any issues here... which OS are you on? Which version of IDEA?

**Comment by airborn** [comment]
Ach, maybe that is the case... I'm stuck with 2016.1.2 under Windows 7
