### ISSUE TITLE
Button focused but nothing to show?

### ISSUE THREAD

**Issue by xinkunZ** [mallowigi/material-theme-jetbrains-extended#20]
I like this UI very much. A problem is  when button focused, there is no border or something to show, so I could not find which button is focused.  My own IDEA plugin using up left down and right key to choose a button . Please fix it! THANKS!!

**Comment by mallowigi** [comment]
Issued a release

**Comment by mallowigi** [comment]
Can we close this issue then?

**Comment by xinkunZ** [comment]
@mallowigi   There is a small problem with button focused background color width. see the picture please. 

Thanks!

![1](https://cloud.githubusercontent.com/assets/7759897/25847062/0f4e9b66-34e7-11e7-94c2-f057fdba4630.png)

**Comment by mallowigi** [comment]
Ok that should do the trick

**Comment by xinkunZ** [comment]
@mallowigi  thanks.  you can close this issue!
