### ISSUE TITLE
Panel Output

### ISSUE THREAD

**Issue by Eric-Jackson** [mallowigi/material-theme-jetbrains-extended#24]
Not able to see the output in the event log with Palenight UI + Lighter editor.

![screen shot 2017-05-09 at 10 34 22 am](https://cloud.githubusercontent.com/assets/1268260/25856193/49a603ba-34a3-11e7-9908-7bfb3c08dcf4.png)
![screen shot 2017-05-09 at 10 34 18 am](https://cloud.githubusercontent.com/assets/1268260/25856198/4ba5293e-34a3-11e7-9497-d88083c065b3.png)

**Comment by Eric-Jackson** [comment]
Getting the same in the terminal: 
![screen shot 2017-05-09 at 10 41 32 am](https://cloud.githubusercontent.com/assets/1268260/25856489/2617ba28-34a4-11e7-8cd3-fa292a910fd5.png)

**Comment by mallowigi** [comment]
Thanks for this. Should be fixed
