### ISSUE TITLE
Menu items doesn't all have the same color

### ISSUE THREAD

**Issue by Kendos-Kenlen** [mallowigi/material-theme-jetbrains-extended#27]
Hi,

When using some menus, some elements doesn't use the correct color and use a darker grey instead of the lighter color used everywhere else.

This make hard to distinguish disabled items and this darkened items.

(None of the menus items are disabled in the screenshot)

![screenshot_20170516_120223](https://cloud.githubusercontent.com/assets/2579741/26101018/068dfa6e-3a30-11e7-84a4-eb4b1a13e2ad.png)

**Comment by mallowigi** [comment]
Seems like an issue with the darker theme

**Comment by nazrhyn** [comment]
**Default**   
![image](https://cloud.githubusercontent.com/assets/1672405/26128643/24652028-3a5b-11e7-978d-62e66235fa73.png)

**Darker**
![image](https://cloud.githubusercontent.com/assets/1672405/26128668/38822ce0-3a5b-11e7-9acb-8191363fe8ed.png)

Seems like any item that expands gets the "disabled" looking text, while any item that does not gets the right color.

**Comment by mallowigi** [comment]
should be fixed now
