### ISSUE TITLE
No Font change (Intellij Latest Version 2017.1.2)

### ISSUE THREAD

**Issue by HGGamers** [mallowigi/material-theme-jetbrains-extended#28]
Im using this plugin on the latest intellij Version (2017.1.2) and if i selecte the scheme it look like that: https://prnt.sc/f8hs2z  and i just installed the plugin and did not change settings or anything like that just seltected the Material Theme - Default scheme and all other schemes from material theme has that same font like the default material theme scheme

**Comment by Kendos-Kenlen** [comment]
Nothing looks abnormal. The color scheme comes with Fira Code font (size 13 with line space 1.4).

As far as I know, it's not possible to share a color scheme without the associated font.

**Comment by HGGamers** [comment]
Oh ok sry thoght the font looks like the original Material Theme Plugin
