### ISSUE TITLE
Reduce default line spacing

### ISSUE THREAD

**Issue by Kendos-Kenlen** [mallowigi/material-theme-jetbrains-extended#29]
Hi,

Currently, the line spacing is set to 1.4. I think it's a bit too big. Keeping the Darcula default would be better (1.0), the code definitely looks better with it and it's closer to the "expected behaviour" I think.

Sincerely,

**Comment by mallowigi** [comment]
I myself prefer 1.2, so it's highly opinionated. Maybe let the people vote?

**Comment by nazrhyn** [comment]
If anything, I'd say it should follow the example from the built-in themes. Though, it's a simple matter of cloning the theme and tweaking it.
