### ISSUE TITLE
memory indicator bar vs. text contrast

### ISSUE THREAD

**Issue by nazrhyn** [mallowigi/material-theme-jetbrains-extended#31]
Hello again.

![memory-usage](https://cloud.githubusercontent.com/assets/1672405/26128337/1db5300c-3a5a-11e7-9893-872bb2697f39.png)

I noticed you'd updated the Memory Indicator in version 0.3.6.1. I guess it's probably just using the standard text foreground color that all other stuff in the status bar is using, but with that light blue progress bar color, it's pretty hard to read.

You'll probably tell me it's WIP and that's fine :wink:.

Thanks, again; it's cool seeing these tweaks and updates happen.

**Comment by mallowigi** [comment]
I know it's a mistake on the nondefault themes :) it will be fixed on the next release
