### ISSUE TITLE
Scheme's reset to Darcula each run

### ISSUE THREAD

**Issue by kerbyfc** [mallowigi/material-theme-jetbrains-extended#32]
Hi!

Each time I run IDE it restores Darkula color scheme. It can be reproduced only with activated material-theme-jetbrains-extended plugin.

WebStorm 2017.1.2
Build #WS-171.4249.40, built on April 25, 2017
Licensed to User

JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

**Comment by mallowigi** [comment]
I don't know how to reproduce this, as far as I'm concerned the color scheme is not changing at each restart...

maybe there is an error causing the plugin to load Darcula? Do you have errors popping up?

**Comment by mallowigi** [comment]
Closing due to lack of response.
