### ISSUE TITLE
Extended terminal load delay after 0.3.7 update

### ISSUE THREAD

**Issue by kunagpal** [mallowigi/material-theme-jetbrains-extended#34]
WebStorm: 2017.1.3
OS: OSX Sierra 10.12.4
Plugin versions: >= v0.3.7

Upon toggling the inbuilt IDE terminal, the following can be seen for several seconds

<img width="1440" alt="screen shot 2017-05-21 at 15 50 11" src="https://cloud.githubusercontent.com/assets/7289840/26283043/415a6630-3e3d-11e7-9aca-392ad5f5dfb4.png">

**Comment by mallowigi** [comment]
Looks like an issue with Webstorm. It happens even when I disable the plugin.

**Comment by kunagpal** [comment]
Thanks for the heads up, I'll put the issue up on the right tracker 😄
