### ISSUE TITLE
Change shade of blue for modified files

### ISSUE THREAD

**Issue by karanrajpal14** [mallowigi/material-theme-jetbrains-extended#7]
Would you please change the shade of the blue color in the tabs which contain the filename for modified files? It currently uses a dark blue that's hard to read when something like [f.lux](https://justgetflux.com/) is enabled. Can barely read the filenames with the current shade.

**Comment by mallowigi** [comment]
Feel free to submit a PR if you'd like to :)

**Comment by karanrajpal14** [comment]
I'd like to help but I've never contributed to any project before. I did find some documentation on how to. I  became a little over-enthusiastic and even forked the project and cloned it :P But, I have no idea where to look and change things. I am looking at colors/Material Theme - Default.xml right now and I couldn't understand where to change it. Could you please point me in the right direction? I'd appreciate that.

**Comment by mallowigi** [comment]
Still relevant?

**Comment by karanrajpal14** [comment]
Well, I don't know if anything can be done about it right now since you've introduced some changes that Studio won't be able to support until it gets an update. What do you think? Close it now and see if it's any better later?

**Comment by nazrhyn** [comment]
Under **Editor > Colors & Fonts > File Status**, it is possible to configure the color for some of these file statuses; however, in the latest version of WebStorm, for some reason, it's now restricted to only the **Default** or **Darkula** scheme. Before, it was possible to modify them for any theme.

![image](https://cloud.githubusercontent.com/assets/1672405/26128545/c0b6155a-3a5a-11e7-9789-f4c95e0c8649.png)

I'm not sure why they did that... _but_, if you're using one of those, you might be able to modify this yourself.

**Comment by mallowigi** [comment]
They did that because they are working on extracting file colors to the appearance section instead of editor and colors.

I don't know how the implementation will be or when but im planning on implementing a file colors plugin that will override any file colors.

In any case I still can't do anything about android studio :(

**Comment by nazrhyn** [comment]
Ahh, interesting. Thanks for that information; I really wondered what was going on there. :+1:

**Comment by karanrajpal14** [comment]
@mallowigi no. I think it's better to close this since AS v3.0 will be able to use the latest update of your theme and my issue should be resolved then. If not, I shall reopen it later. Thank you for the help!
